### ISSUE TITLE
blazerStringHttpMessageConverter的bean报错

### ISSUE THREAD

**Issue by decm32** [Char-CN/data-service#1]
Multiple annotations found at this line:
	- Class dependency error 'MediaType' occurred on aspect definition 'Aspect definition [\data-service\src\main\resources
	 \applicationContext.xml:120] advise type [after] advise [org.springframework.transaction.interceptor.TransactionInterceptor.invoke]' while 
	 processing bean 'blazerStringHttpMessageConverter (22) [org.blazer.dataservice.util.UTF8StringHttpMessageConverter]'. Check if builder 
	 classpath is complete
	- Class dependency error 'MediaType' occurred on aspect definition 'Aspect definition [\data-service\src\test\resources
	 \applicationContext.xml:79] advise type [after] advise [org.springframework.transaction.interceptor.TransactionInterceptor.invoke]' while 
	 processing bean 'blazerStringHttpMessageConverter (22) [org.blazer.dataservice.util.UTF8StringHttpMessageConverter]'. Check if builder 
	 classpath is complete

何总速查

**Comment by Char-CN** [comment]
你自己的eclipse环境那么差，还怪我
